DROP TABLE IF EXISTS transactions;
ALTER TABLE assets DROP COLUMN IF EXISTS user_id;
ALTER TABLE assets DROP COLUMN IF EXISTS ticker;
ALTER TABLE assets DROP COLUMN IF EXISTS asset_type;
ALTER TABLE assets DROP COLUMN IF EXISTS quantity;
ALTER TABLE assets DROP COLUMN IF EXISTS avg_price;
ALTER TABLE assets DROP COLUMN IF EXISTS created_at;
